##
# brews
##
brew "curl"
brew "direnv"
brew "gifsicle"
brew "git"
brew "git-lfs"
brew "gpg"
brew "heroku"
brew "hub"
brew "iproute2mac"
brew "nmap"
brew "nvm"
brew "openssl"
brew "readline"
brew "shellcheck"
brew "tldr"
brew "tree"
brew "wget"
brew "wireshark"
brew "wrk"
brew "yarn"
brew "youtube-dl"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

##
# casks
##
tap "caskroom/drivers"
tap "caskroom/versions"

cask "1password"
cask "adobe-acrobat-reader"
cask "android-file-transfer"
cask "boostnote"
cask "caffeine"
cask "cd-to"
cask "dash"
cask "docker"
cask "dropbox"
cask "fiddler" # installation fails
cask "firefox"
cask "google-chrome"
cask "gpgtools-beta"
cask "handbrake"
cask "inssider"
cask "intellij-idea-ce"
cask "iterm2"
cask "java"
cask "keepassxc"
cask "keka"
cask "libreoffice"
cask "licecap"
# cask "logitech-harmony" # untrusted certificate
cask "macvim"
cask "microsoft-office"
cask "psequel"
cask "sabnzbd"
cask "sequel-pro"
cask "skype"
cask "slack"
cask "spectacle"
cask "spotify"
cask "steam"
cask "synology-cloud-station-drive"
cask "synology-photo-station-uploader"
cask "teamviewer"
cask "telegram"
cask "transmit"
cask "tunnelblick"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "vmware-fusion"
cask "whatsapp"

# QuickLook plugins
cask "qlcolorcode"
cask "qlstephen"
cask "qlmarkdown"
cask "quicklook-json"
cask "betterzipql"
cask "suspicious-package"
